
# Your Gemini API Key
gemini.api.key= ${GEMINI_API_KEY}

# The Gemini API endpoint
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent

# H2 Database Console (Optional, but good for debugging)
# This lets you see your database at http://localhost:8080/h2-console


# Database settings
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Email Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Add these properties for reading email

spring.mail.imap.host=imap.gmail.com
spring.mail.imap.port=993
spring.mail.imap.ssl.enable=true
spring.mail.imap.auth.mechanisms=XOAUTH2
spring.mail.properties.mail.imap.ssl.trust=imap.gmail.com
# Use the same username/password as your sender
# spring.mail.username=your-new-account@gmail.com
# spring.mail.password=your-16-digit-app-password
spring.mail.username=${spring.mail.username}
spring.mail.password=${spring.mail.password}
escalation.email.to=${escalation.email.to}

sendgrid.api.key=${SENDGRID_API_KEY}